version: "3.7"

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - mcw
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  mcw:
    image: mcw
    container_name: mcw
    build: ./flask_app
    ports:
      - 5000:5000

networks:
  default:
    external:
      name: my-network

  #caddy:
  #  container_name: caddy
  #  image: abdulsalamdocker/caddy:1.0.3-no-stats
  #  restart: unless-stopped
  #  env_file:
  #    - ./env/caddy.env
  #  volumes:
  #    - ./Caddyfile:/etc/Caddyfile:ro
  #    - $HOME/.caddy:/root/.caddy
  #  ports:
  #    - 80:80
  #    - 443:443
  #    - 2015:2015