version: "3.7"

services:
  mcw:
    image: mcw
    restart: always
    container_name: mcw
    privileged: true
    build: ./flask_app
    ports:
      - 5000:5000

networks:
  default:
    external:
      name: my-network-pi